on:
  pull_request:
    branches:
      - master
    paths:
      - 'statshouse-ui/**'
jobs:
  ci-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: 'statshouse-ui'
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: CI=true npm run test
